base.url=https://login.salesforce.com/?locale=in
api.url=https://api.salesforce.com/v1

timeout.default=30
timeout.navigation=60
timeout.assertion=10

browser.type=chrome
browser.headless=false
browser.viewport.width=1920
browser.viewport.height=1080

retry.max=2
retry.screenshot.enabled=true
retry.video.enabled=true

admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}

user.username=${USER_USERNAME}
user.password=${USER_PASSWORD}
